server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /community
spring:
  datasource:
    url: jdbc:mysql://114.132.182.241:3306/discussion_community?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: MyPassword@333
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 50
      max-wait: 60000
  # 开启表单提交 REST风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: kuneychen@foxmail.com
    password: vmiplunbrwuxbafj
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl