server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /community
spring:
  datasource:
    url: jdbc:mysql://114.132.182.241:3306/discussion_community?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: MyPassword@333
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 50
      max-wait: 60000
  # 开启表单提交 REST风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: true
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: kuneychen@foxmail.com
    password: vmiplunbrwuxbafj
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 114.132.182.241
    port: 6379
    password: MyPassword@333
  kafka:
    bootstrap-servers: 114.132.182.241:9092
    consumer:
      enable-auto-commit: true
      group-id: community-consumer-group
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  host: localhost
  port: 9200